version: '3.8'

services:
  ubuntu1:
    build: .
    ports:
      - "2221:22"
  ubuntu2:
    build: .
    ports:
      - "2222:22"
  ubuntu3:
    build: .
    ports:
      - "2223:22"
  ubuntu4:
    build: .
    ports:
      - "2224:22"
  ubuntu5:
    build: .
    ports:
      - "2225:22"